### ISSUE TITLE
setState doesn't not replace, it merges.

### ISSUE THREAD

**Issue by tmbtech** [coderjonny/react-style-guide#4]
This part of the readme should be updated.

```
this.setState({ isEditing: true });
   ... (later) ... 
this.setState({ isActive: true }); // isEditing no longer part of state
```

setState doesn't replace the entire state object, it merges. I think you are referring to `React.replaceState()`
https://facebook.github.io/react/docs/component-api.html#setstate

**Comment by tmbtech** [comment]
check out AirBnB's repo, they have a good react best practice guide. Maybe add a link to the bottom of the readme?

https://github.com/airbnb/javascript/tree/master/react

**Comment by coderjonny** [comment]
Thanks Robbie! 

I should update the style guide for es6 syntax after your talk. :+1:
